

module Shelves

export codex


codex = [
    "j136l7"	=> "__ __ tw xr __ wt __ uv yq so __ qy ",
    "j167l2"	=> "vu __ __ __ rx wt __ uv yq __ os qy ",
    "j17"	=> "__ __ tu __ rw wr __ ut __ sv oq qo ",
    "j17l2"	=> "vs __ __ __ rw wr __ ut __ sv oq qo ",
    "j236"	=> "vv zq __ xs __ wu __ uw yr __ __ qz ",
    "j23k6"	=> "vv zq __ xs __ wu __ uw __ __ ot qz ",
    "j23"	=> "vv zq __ xs __ wu __ uw __ sx __ qz ",
    "j246l3"	=> "vv zq to __ ry __ __ uw yr __ __ qz ",
    "j256"	=> "qr vp __ __ pv rq wo __ uy __ __ ow ",
    "j25"	=> "qr vp __ __ pv rq wo __ __ yu __ ow ",
    "j25l6"	=> "or qp __ __ tv pq ro ws __ __ __ sw ",
    "j26"	=> "vv zq __ __ ry wu __ uw yr __ __ qz ",
    "j26l34"	=> "vv zq to xs __ __ __ uw yr __ __ qz ",
    "j26l3"	=> "vv zq to __ __ wu __ uw yr __ __ qz ",
    "j2k34"	=> "or qp __ __ __ pq ro ws __ uu __ sw ",
    "j2k56"	=> "vv zq __ __ ry wu __ __ yr __ ot qz ",
    "j2k56m4"	=> "vv zq __ __ ry __ __ uw yr __ ot qz ",
    "j2k5"	=> "qr vp __ __ pv rq __ __ uy yu __ ow ",
    "j2k6"	=> "vv zq __ __ ry wu __ uw __ __ ot qz ",
    "j2k6m5"	=> "vv zq __ __ ry wu __ __ __ sx ot qz ",
    "j2k6l3"	=> "vv zq to __ __ wu __ uw __ __ ot qz ",
    "j2"	=> "vv zq __ __ ry wu __ uw __ sx __ qz ",
    "j2l3"	=> "vv zq to __ __ wu __ uw __ sx __ qz ",
    "j346l5"	=> "yr __ ot qz vv zq __ __ ry __ __ uw ",
    "j34k6"	=> "vt __ tv pq ro __ __ uu __ __ or qp ",
    "j36"	=> "vu __ tw xr __ wt __ uv yq __ __ qy ",
    "j3k56m4"	=> "vo __ ty xu __ __ __ ux yt __ ov qq ",
    "j3k5m4"	=> "vu __ tw xr __ __ __ uv yq so __ qy ",
    "j3k5"	=> "yr __ ot qz __ zq __ __ ry wu __ uw ",
    "j3k6"	=> "vo __ ty xu __ ww __ ux __ __ ov qq ",
    "j3"	=> "vt __ tv xq __ ws __ uu __ sw __ qx ",
    "j56"	=> "xr __ wt __ uv yq so __ qy __ __ tw ",
    "j56l7"	=> "xr __ wt __ uv yq so __ qy vu __ __ ",
    "j5"	=> "wr __ ut __ sv oq qo __ __ tu __ rw ",
    "j5l6"	=> "wr __ ut __ sv oq qo vs __ __ __ rw ",
    "j6"	=> "vu __ tw __ rx wt __ uv yq __ __ qy ",
    "k125"	=> "__ sx __ qz vv zq __ __ ry wu __ uw ",
    "k12j5"	=> "__ sx __ qz vv zq to __ __ wu __ uw ",
    "k12"	=> "__ sx __ qz vv zq __ xs __ wu __ uw ",
    "k135m4"	=> "__ rx wt __ __ yq __ os qy vu __ tw ",
    "k157m6"	=> "vv zq to __ ry wu __ __ yr __ __ qz ",
    "k15"	=> "__ rx wt __ uv yq __ __ qy vu __ tw ",
    "k17j5"	=> "or qp vt __ tv pq ro __ __ uu __ __ ",
    "k1j56l7"	=> "__ ux yt __ ov qq vo __ ty xu __ __ ",
    "k1j5"	=> "__ ux yt __ ov qq vo __ __ xu __ ww ",
    "k1j6l7"	=> "__ rx wt __ uv yq __ os qy vu __ __ ",
    "k1j6"	=> "__ zq to __ ry wu __ uw yr __ __ qz ",
    "k1"	=> "__ qx vt __ tv xq __ ws __ uu __ sw ",
    "k256"	=> "vp __ __ pv rq wo __ __ yu __ ow qr ",
    "k257m1"	=> "yr __ ot qz vv zq __ __ ry wu __ __ ",
    "k25m17"	=> "__ sx ot qz vv zq __ __ ry wu __ __ ",
    "k25m1"	=> "__ __ ot qz vv zq __ __ ry wu __ uw ",
    "k25"	=> "yr __ __ qz vv zq __ __ ry wu __ uw ",
    "k26"	=> "vp __ __ pv rq wo __ uy __ __ ow qr ",
    "k26m5"	=> "vt __ __ pq ro ws __ __ __ sw or qp ",
    "k2j17"	=> "__ __ __ pq ro ws __ uu __ sw or qp ",
    "k2j56l7"	=> "yr __ __ qz vv zq to __ ry wu __ __ ",
    "k2j56"	=> "yr __ __ qz vv zq to __ ry __ __ uw ",
    "k2j5m1"	=> "__ __ ot qz vv zq to __ __ wu __ uw ",
    "k2j5l6"	=> "yr __ __ qz vv zq to xs __ __ __ uw ",
    "k2j5"	=> "yr __ __ qz vv zq to __ __ wu __ uw ",
    "k2j6"	=> "vp __ __ pv rq wo __ uy yu __ __ qr ",
    "k2m1"	=> "__ __ ot qz vv zq __ xs __ wu __ uw ",
    "k2"	=> "yr __ __ qz vv zq __ xs __ wu __ uw ",
    "k345m2"	=> "xr __ __ __ uv yq so __ qy vu __ tw ",
    "k34"	=> "wr __ ut __ __ oq qo vs __ tu __ rw ",
    "k34m2"	=> "wr __ __ __ sv oq qo vs __ tu __ rw ",
    "k56"	=> "vu __ tw __ rx wt __ __ yq __ os qy ",
    "k56m4"	=> "vu __ tw __ rx __ __ uv yq __ os qy ",
    "k5"	=> "xr __ wt __ uv yq __ __ qy vu __ tw ",
    "k6"	=> "vs __ tu __ rw wr __ ut __ __ oq qo ",
    "k6m5"	=> "vs __ tu __ rw wr __ __ __ sv oq qo ",
    "n0"	=> "vr __ tt __ rv wq __ us __ su __ qw ",
    "n167m4"	=> "vu __ __ xr __ wt __ uv yq so __ qy ",
    "n167"	=> "yr __ __ qz __ zq to __ ry wu __ uw ",
    "n25m6"	=> "or qp vt __ __ pq ro ws __ __ __ sw ",
    "n26l5"	=> "__ __ tv pq ro ws __ __ __ sw or qp ",
    "n345l7"	=> "__ rx __ __ uv yq __ os qy vu __ tw ",
    "n345"	=> "__ zq __ __ ry wu __ uw yr __ ot qz ",
    "n45l2"	=> "vo __ __ xu __ ww __ ux yt __ ov qq ",
    "n5l2"	=> "vp __ __ pv rq __ __ uy yu __ ow qr ",
    "n67m2"	=> "__ ux __ __ ov qq vo __ ty xu __ ww ",
    "n6m2"	=> "qr vp __ __ pv rq wo __ uy yu __ __ ",
]


end # module


